There's a lot here
columbus-elixir/marketing pull request #48
Opened 2018-05-01 23:33 UTC by EmjayFlight

Admin board
Speaker CRUD request
Basic Auth
Authorization

2018-08-06 15:15 UTC, Kartstig commented on lib/cbus_elixir/accounts/accounts.ex
> +    with user when is_map(user) <- Repo.get(User, user_id), do: user.sessions
I'm not sure what this will return if there's no `else` to match this `with`... I feel like the error should be handled or `[]` should be returned.

2018-08-06 15:16 UTC, Kartstig commented on lib/cbus_elixir/accounts/accounts.ex
> +  alias CbusElixir.{Accounts.User, Repo}
Can you split these out like we've been doing on other modules? We prefer multi-line aliases for readability

2018-08-06 15:18 UTC, Kartstig commented on assets/js/app.js
> +$(document).ready(function(){
Why are there 2 instances of `$(document).ready`?

2018-08-06 15:18 UTC, Kartstig commented on assets/js/socket.js
> +
extra

2018-08-06 15:21 UTC, Kartstig commented on lib/cbus_elixir_web/controllers/speaker_controller.ex
> +        #|> redirect(to: speaker_path(conn, :show, speaker))
Delete?

2018-08-06 15:22 UTC, Kartstig commented on lib/cbus_elixir_web/email.ex
> +    |>to(email)
You'll probably want to run `mix format` on your changed files

2018-08-06 15:23 UTC, Kartstig commented on lib/cbus_elixir_web/email.ex
> +    |>from("memjay3279@gmail.com")
We're going to want to use an official Columbus Elixir email. I'll get back to you on which one to use...

2018-08-06 15:23 UTC, Kartstig commented on lib/cbus_elixir_web/email.ex
> +    |>from("memjay3279@gmail.com")
same as above

2018-08-06 15:23 UTC, Kartstig commented on lib/cbus_elixir_web/email.ex
> +    |>from("memjay3279@gmail.com")
same as above

2018-08-06 15:24 UTC, Kartstig commented on lib/cbus_elixir_web/email.ex
> +    |>from("memjay3279@gmail.com")
same as above

2018-08-06 15:24 UTC, KimmestOfChis commented
@Kartstig Hey man, thanks for taking a look! @robsdudeson and I have been coding in phoenix for the last month and there's a lot we would do differently. We'll also need to make some ScriptDrop specific changes in the future. We'll be at the meet up tomorrow and we should talk about features you guys liked/the ones you want to scrap. 

We'll likely scrap this PR and make a smaller, more focused one or many.

2018-08-06 15:25 UTC, Kartstig commented on lib/cbus_elixir_web/templates/page/index.html.eex
> +        <h2 class="title myriad">What is Columbus Elixir?</h2>
:heart:

2018-08-06 15:29 UTC, Kartstig commented on priv/repo/migrations/20180421181224_add_status_to_speakers.exs
> +      add :status, :string
You're going to have to remove the `email` and `name` field which got put on `Users`

2018-08-06 15:32 UTC, Kartstig requested changes
There are a lot of changes here, and we really appreciate your effort.

I will do a more thorough review once some of the initial items have been resolved.

Great work so far, and thanks for adding tests

2018-12-14 15:56 UTC, robsdudeson commented
@EmjayFlight I think we can probably close this out without merge.  Thoughts?

2018-12-14 16:03 UTC, EmjayFlight commented
> @EmjayFlight I think we can probably close this out without merge. Thoughts?

Agreed

2019-01-22 00:26 UTC, closed without merging