Added eastern timezone
columbus-elixir/marketing pull request #68
Opened 2019-02-06 17:47 UTC by croz1007

2019-02-06 17:48 UTC, ieatkimchi submitted a review, later dismissed
🚢

2019-02-06 23:06 UTC, ieatkimchi approved these changes

2019-02-06 23:07 UTC, ieatkimchi requested changes

2019-02-06 23:07 UTC, ieatkimchi commented on lib/cbus_elixir_web/controllers/speaker_controller.ex
> +  # plug(
should be bring this back?

2019-02-06 23:35 UTC, croz1007 commented on lib/cbus_elixir_web/controllers/speaker_controller.ex
> +  # plug(
Done

2019-02-07 00:20 UTC, ieatkimchi approved these changes

2019-02-07 00:47 UTC, merged